# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: npm-publish
on:
  push:
    paths:
      - ".github/workflows/*.yml"
      - "src/**/*.*"
# on:
#   workflow_dispatch:
#     inputs:
#       logLevel:
#         description: 'Log level'
#         required: true
#         default: 'warning'
#         type: choice
#         options:
#         - info
#         - warning
#         - debug

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
        run: |
          npm i pnpm -g
          pnpm -v
      - name: 安装依赖并执行打包    
      - run: |
          pnpm install
          pnpm build
      - name: 更新版本号
        run: npm version patch
      - run: echo npm view pnpm version
      - name: 发布到npm   
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
